select * from tabela_de_produtos;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA,
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PREÇO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRECO EM CONTA'
    ELSE 'PRECO BARATO'
END AS STATUS_PRECO
FROM tabela_de_produtos;

SELECT EMBALAGEM,
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PREÇO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRECO EM CONTA'
    ELSE 'PRECO BARATO'
END AS STATUS_PRECO, avg(preco_de_lista) as PRECO_MEDIO
FROM tabela_de_produtos
group by embalagem,
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PREÇO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRECO EM CONTA'
    ELSE 'PRECO BARATO'
END;


SELECT EMBALAGEM,SABOR,
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PREÇO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRECO EM CONTA'
    ELSE 'PRECO BARATO'
END AS STATUS_PRECO, avg(preco_de_lista) as PRECO_MEDIO
FROM tabela_de_produtos
where sabor = 'manga'
group by embalagem,
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'PREÇO CARO'
    WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRECO EM CONTA'
    ELSE 'PRECO BARATO'
END;
