SELECT ESTADO , sum(LIMITE_DE_CREDITO) FROM tabela_de_clientes
group by ESTADO;

SELECT ESTADO , sum(LIMITE_DE_CREDITO) FROM tabela_de_clientes
group by ESTADO
HAVING sum(LIMITE_DE_CREDITO) > 900000;

SELECT EMBALAGEM, max(PRECO_DE_LISTA), min(PRECO_DE_LISTA) FROM tabela_de_produtos
GROUP BY EMBALAGEM;

SELECT EMBALAGEM, max(PRECO_DE_LISTA), min(PRECO_DE_LISTA) FROM tabela_de_produtos
GROUP BY EMBALAGEM HAVING sum(PRECO_DE_LISTA) <= 80;

SELECT EMBALAGEM, max(PRECO_DE_LISTA), min(PRECO_DE_LISTA) FROM tabela_de_produtos
GROUP BY EMBALAGEM HAVING sum(PRECO_DE_LISTA) <= 80 AND mAX(PRECO_DE_LISTA) >= 5;