SELECT NOME, TIMESTAMPDIFF (YEAR, DATA_DE_NASCIMENTO, CURDATE()) AS    IDADE
FROM  tabela_de_clientes;

SELECT NOME, (year(CURRENT_DATE()) - year(DATA_DE_NASCIMENTO)) AS IDADE FROM tabela_de_clientes;

SELECT NOME, (year(CURRENT_TIMESTAMP()) - year(DATA_DE_NASCIMENTO)) AS IDADE FROM tabela_de_clientes;