SELECT CONCAT('O cliente ', TC.NOME, ' faturou ', 
CAST(SUM(INF.QUANTIDADE * INF.preco) AS char (20))
 , ' no ano ', CAST(YEAR(NF.DATA_VENDA) AS char (20))) AS SENTENCA FROM notas_fiscais NF
INNER JOIN itens_notas_fiscais INF ON NF.NUMERO = INF.NUMERO
INNER JOIN tabela_de_clientes TC ON NF.CPF = TC.CPF
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY TC.NOME, YEAR(DATA_VENDA);

SELECT CONCAT('O cliente ', NOME,' faturou ', round(SUM(QUANTIDADE*PRECO)),' no ano de ', YEAR(NF.DATA_VENDA)) AS RESULTADO
FROM TABELA_DE_CLIENTES A
INNER JOIN NOTAS_FISCAIS NF ON A.CPF=NF.CPF
INNER JOIN ITENS_NOTAS_FISCAIS INF ON INF.NUMERO=NF.NUMERO
WHERE YEAR(DATA_VENDA)=2016
GROUP BY NOME,YEAR(DATA_VENDA);