SELECT * FROM tbcliente;

SELECT * FROM tbcliente WHERE DATA_NASCIMENTO = '1995-01-13';

SELECT * FROM tbcliente WHERE DATA_NASCIMENTO > '1995-01-13';

SELECT * FROM tbcliente WHERE DATA_NASCIMENTO >= '1995-01-13';

SELECT * FROM tbcliente WHERE year(DATA_NASCIMENTO) = 1995;

SELECT * FROM tbcliente where month(DATA_NASCIMENTO) = 8;